import { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {
  Sparkles,
  RefreshCw,
  Copy,
  Download,
  GitPullRequest,
  Eye,
  Edit3,
  Code,
  CheckCircle,
  FileText,
} from 'lucide-react';
import { cn } from '../utils/cn';
import { generateReadme } from '../lib/api';

const DEFAULT_OPTIONS = {
  badges: true,
  features: true,
  installation: true,
  usage: true,
  apiRef: false,
  contributing: true,
  license: true,
};

function extractRepoName(url: string): string {
  try {
    const clean = url.replace('https://github.com/', '').replace('http://github.com/', '');
    const parts = clean.split('/');
    return parts.length >= 2 ? `${parts[0]}/${parts[1]}` : url;
  } catch {
    return url;
  }
}

function generateReadmeLocal(repo: string, options: typeof DEFAULT_OPTIONS): string {
  const parts = repo.split('/');
  const name = parts[1] || 'Project';
  const capitalized = name.charAt(0).toUpperCase() + name.slice(1).replace(/-/g, ' ');
  const owner = parts[0] || 'owner';

  const lines: string[] = [];

  lines.push(`# ${capitalized}\n`);

  if (options.badges) {
    lines.push(
      `![GitHub stars](https://img.shields.io/github/stars/${repo}?style=for-the-badge) ` +
      `![GitHub forks](https://img.shields.io/github/forks/${repo}?style=for-the-badge) ` +
      `![GitHub issues](https://img.shields.io/github/issues/${repo}?style=for-the-badge) ` +
      `![License](https://img.shields.io/github/license/${repo}?style=for-the-badge)\n`
    );
  }

  lines.push(`> A modern, open-source project maintained by [@${owner}](https://github.com/${owner}).\n`);

  if (options.features) {
    lines.push(`## ✨ Features\n`);
    lines.push(
      `- ⚡ **Fast** — designed for performance from the ground up\n` +
      `- 🔧 **Configurable** — sensible defaults with full flexibility\n` +
      `- 📦 **Zero vendor lock-in** — open-source, self-hostable, MIT licensed\n` +
      `- 🧪 **Well tested** — comprehensive test suite with CI/CD\n` +
      `- 📖 **Documented** — thorough API reference and usage examples\n`
    );
  }

  if (options.installation) {
    lines.push(`## 📦 Installation\n`);
    lines.push(
      `### Prerequisites\n\n` +
      `- Node.js 18+ or Python 3.11+\n` +
      `- Git\n\n` +
      `### Clone and install\n\n` +
      `\`\`\`bash\n` +
      `git clone https://github.com/${repo}.git\n` +
      `cd ${name}\n` +
      `npm install\n` +
      `\`\`\`\n\n` +
      `Copy the example environment file and fill in your values:\n\n` +
      `\`\`\`bash\n` +
      `cp .env.example .env\n` +
      `\`\`\`\n`
    );
  }

  if (options.usage) {
    lines.push(`## 🚀 Usage\n`);
    lines.push(
      `### Development\n\n` +
      `\`\`\`bash\n` +
      `npm run dev\n` +
      `\`\`\`\n\n` +
      `### Production build\n\n` +
      `\`\`\`bash\n` +
      `npm run build\n` +
      `npm start\n` +
      `\`\`\`\n\n` +
      `### Quick example\n\n` +
      `\`\`\`typescript\n` +
      `import { ${capitalized.replace(/ /g, '')} } from '${name}';\n\n` +
      `const client = new ${capitalized.replace(/ /g, '')}({\n` +
      `  apiKey: process.env.API_KEY,\n` +
      `});\n\n` +
      `const result = await client.run();\n` +
      `console.log(result);\n` +
      `\`\`\`\n`
    );
  }

  if (options.apiRef) {
    lines.push(`## 📚 API Reference\n`);
    lines.push(
      `### \`GET /api/v1/status\`\n\n` +
      `Returns the current health and status of the service.\n\n` +
      `**Response**\n\n` +
      `\`\`\`json\n` +
      `{\n` +
      `  "status": "ok",\n` +
      `  "version": "1.0.0",\n` +
      `  "uptime": 3600\n` +
      `}\n` +
      `\`\`\`\n`
    );
  }

  if (options.contributing) {
    lines.push(`## 🤝 Contributing\n`);
    lines.push(
      `Contributions are welcome! Here's how to get started:\n\n` +
      `1. Fork the repository\n` +
      `2. Create a feature branch: \`git checkout -b feat/your-feature\`\n` +
      `3. Commit your changes: \`git commit -m 'feat: add your feature'\`\n` +
      `4. Push to your branch: \`git push origin feat/your-feature\`\n` +
      `5. Open a Pull Request\n\n` +
      `Please read our [Code of Conduct](CODE_OF_CONDUCT.md) before contributing.\n`
    );
  }

  if (options.license) {
    lines.push(`## 📄 License\n`);
    lines.push(
      `This project is licensed under the **MIT License** — see the [LICENSE](LICENSE) file for details.\n`
    );
  }

  lines.push(
    `---\n\n` +
    `<p align="center">Generated by <a href="https://github.com/krypthos-org/gitwise-ai">GitWise AI</a> · Powered by Qwen2.5 72B</p>`
  );

  return lines.join('\n');
}

type ViewMode = 'preview' | 'edit' | 'source';

export function ReadmeGeneratorPage() {
  const [repoUrl, setRepoUrl] = useState('https://github.com/krypthos-org/gitwise-ai');
  const [options, setOptions] = useState(DEFAULT_OPTIONS);
  const [loading, setLoading] = useState(false);
  const [content, setContent] = useState('');
  const [repoName, setRepoName] = useState('');
  const [viewMode, setViewMode] = useState<ViewMode>('preview');
  const [copied, setCopied] = useState(false);

  const handleGenerate = async () => {
    if (!repoUrl.trim()) return;
    setLoading(true);
    const name = extractRepoName(repoUrl);
    setRepoName(name);
    try {
      const result = await generateReadme({ repoUrl, options });
      setContent(result.content);
    } catch {
      // fallback to local generation
      setContent(generateReadmeLocal(name, options));
    }
    setViewMode('preview');
    setLoading(false);
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'README.md';
    a.click();
    URL.revokeObjectURL(url);
  };

  const toggleOption = (key: keyof typeof DEFAULT_OPTIONS) => {
    setOptions((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  return (
    <div className="max-w-6xl mx-auto">
      <div className="grid grid-cols-1 lg:grid-cols-[320px_1fr] gap-6">
        {/* Left: config */}
        <div className="space-y-5">
          {/* Input */}
          <div className="bg-zinc-900 border border-zinc-800 rounded-3xl p-5 space-y-5">
            <div className="flex items-center gap-2">
              <FileText className="w-4 h-4 text-amber-400" />
              <span className="text-sm font-semibold text-white">Repository</span>
            </div>

            <div>
              <label className="text-[10px] uppercase tracking-wider text-zinc-500 block mb-2">
                GitHub URL or owner/repo
              </label>
              <input
                type="text"
                value={repoUrl}
                onChange={(e) => setRepoUrl(e.target.value)}
                className="w-full bg-zinc-950 border border-zinc-700 focus:border-amber-500 rounded-xl px-4 py-3 text-sm font-mono outline-none text-zinc-200 placeholder:text-zinc-600 transition-colors"
                placeholder="https://github.com/owner/repo"
              />
            </div>

            {/* Options */}
            <div>
              <label className="text-[10px] uppercase tracking-wider text-zinc-500 block mb-3">
                Sections to Include
              </label>
              <div className="space-y-2">
                {(Object.keys(options) as (keyof typeof DEFAULT_OPTIONS)[]).map((key) => (
                  <label
                    key={key}
                    className="flex items-center gap-3 cursor-pointer group"
                  >
                    <div
                      onClick={() => toggleOption(key)}
                      className={cn(
                        'w-9 h-5 rounded-full transition-colors relative flex-shrink-0',
                        options[key] ? 'bg-amber-500' : 'bg-zinc-700'
                      )}
                    >
                      <div
                        className={cn(
                          'absolute top-0.5 w-4 h-4 bg-white rounded-full shadow transition-all',
                          options[key] ? 'left-[18px]' : 'left-0.5'
                        )}
                      />
                    </div>
                    <span className="text-xs text-zinc-300 capitalize group-hover:text-white transition-colors">
                      {key === 'apiRef' ? 'API Reference' : key.charAt(0).toUpperCase() + key.slice(1)}
                    </span>
                  </label>
                ))}
              </div>
            </div>

            <button
              onClick={handleGenerate}
              disabled={loading || !repoUrl.trim()}
              className="w-full flex items-center justify-center gap-2 bg-amber-500 hover:bg-amber-400 disabled:bg-zinc-800 disabled:text-zinc-600 text-zinc-900 font-bold text-sm py-3 rounded-xl transition-all"
            >
              {loading ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin" />
                  Generating…
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  Generate README
                </>
              )}
            </button>
          </div>

          {/* Actions (when content is ready) */}
          {content && (
            <div className="bg-zinc-900 border border-zinc-800 rounded-3xl p-5 space-y-3">
              <div className="text-[10px] uppercase tracking-wider text-zinc-500 mb-3">Actions</div>

              <button
                onClick={handleCopy}
                className="w-full flex items-center gap-2 text-sm px-4 py-2.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 rounded-xl transition-all font-medium"
              >
                {copied ? <CheckCircle className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
                {copied ? 'Copied!' : 'Copy Markdown'}
              </button>

              <button
                onClick={handleDownload}
                className="w-full flex items-center gap-2 text-sm px-4 py-2.5 bg-zinc-800 hover:bg-zinc-700 text-zinc-200 rounded-xl transition-all font-medium"
              >
                <Download className="w-4 h-4" />
                Download README.md
              </button>

              <button
                disabled={true}
                className="w-full flex items-center gap-2 text-sm px-4 py-2.5 rounded-xl transition-all font-medium bg-zinc-800 text-zinc-500 cursor-not-allowed opacity-60"
              >
                <GitPullRequest className="w-4 h-4" />
                Create GitHub PR (coming soon)
              </button>

              {repoName && (
                <div className="text-xs text-zinc-600 text-center pt-1">
                  For <span className="text-zinc-400 font-mono">{repoName}</span>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Right: preview / editor */}
        <div>
          {!content ? (
            <div className="h-full min-h-96 border border-dashed border-zinc-700 rounded-3xl flex items-center justify-center">
              <div className="text-center px-6">
                <div className="w-14 h-14 rounded-2xl bg-zinc-900 border border-zinc-800 flex items-center justify-center mx-auto mb-4">
                  <FileText className="w-6 h-6 text-zinc-600" />
                </div>
                <div className="text-sm font-medium text-zinc-400 mb-2">
                  Your README preview will appear here
                </div>
                <div className="text-xs text-zinc-600 max-w-xs">
                  Enter a GitHub repo URL, select sections, and hit Generate. Qwen2.5 72B will write it for you.
                </div>
              </div>
            </div>
          ) : (
            <div className="bg-zinc-900 border border-zinc-800 rounded-3xl overflow-hidden flex flex-col">
              {/* Tab bar */}
              <div className="border-b border-zinc-800 px-5 py-3 flex items-center gap-1">
                {([
                  { mode: 'preview' as ViewMode, icon: Eye, label: 'Preview' },
                  { mode: 'edit' as ViewMode, icon: Edit3, label: 'Edit' },
                  { mode: 'source' as ViewMode, icon: Code, label: 'Source' },
                ] as const).map(({ mode, icon: Icon, label }) => (
                  <button
                    key={mode}
                    onClick={() => setViewMode(mode)}
                    className={cn(
                      'flex items-center gap-1.5 text-xs px-3 py-1.5 rounded-lg transition-all font-medium',
                      viewMode === mode
                        ? 'bg-white text-zinc-900'
                        : 'text-zinc-500 hover:text-zinc-300 hover:bg-zinc-800'
                    )}
                  >
                    <Icon className="w-3.5 h-3.5" />
                    {label}
                  </button>
                ))}
                <div className="ml-auto text-[10px] text-zinc-600">
                  {content.length} chars · ~{Math.ceil(content.split('\n').length)} lines
                </div>
              </div>

              {/* Content */}
              <div className="flex-1 overflow-auto" style={{ maxHeight: '70vh' }}>
                {viewMode === 'preview' && (
                  <div className="px-8 py-6 prose-readme">
                    <MarkdownPreview content={content} />
                  </div>
                )}
                {viewMode === 'edit' && (
                  <textarea
                    value={content}
                    onChange={(e) => setContent(e.target.value)}
                    className="w-full h-full min-h-96 bg-transparent px-6 py-5 text-sm font-mono text-zinc-300 outline-none resize-none"
                    style={{ minHeight: '500px' }}
                  />
                )}
                {viewMode === 'source' && (
                  <pre className="px-6 py-5 text-xs font-mono text-zinc-400 whitespace-pre-wrap leading-relaxed overflow-auto">
                    {content}
                  </pre>
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function MarkdownPreview({ content }: { content: string }) {
  return (
    <div className="text-zinc-300 text-sm leading-relaxed [&_h1]:text-2xl [&_h1]:font-bold [&_h1]:text-white [&_h1]:mb-4 [&_h1]:mt-6 [&_h2]:text-lg [&_h2]:font-semibold [&_h2]:text-white [&_h2]:mt-8 [&_h2]:mb-3 [&_h3]:text-base [&_h3]:font-semibold [&_h3]:text-zinc-200 [&_h3]:mt-6 [&_h3]:mb-2 [&_p]:mb-3 [&_p]:leading-relaxed [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:mb-3 [&_ul_li]:mb-1 [&_ol]:list-decimal [&_ol]:pl-5 [&_ol]:mb-3 [&_ol_li]:mb-1 [&_code]:bg-zinc-800 [&_code]:text-amber-300 [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:rounded [&_code]:text-xs [&_code]:font-mono [&_pre]:bg-zinc-950 [&_pre]:border [&_pre]:border-zinc-800 [&_pre]:rounded-xl [&_pre]:p-4 [&_pre]:overflow-x-auto [&_pre]:mb-4 [&_pre_code]:bg-transparent [&_pre_code]:text-zinc-300 [&_pre_code]:p-0 [&_a]:text-violet-400 [&_a]:underline [&_a]:underline-offset-2 [&_a:hover]:text-violet-300 [&_blockquote]:border-l-2 [&_blockquote]:border-zinc-700 [&_blockquote]:pl-4 [&_blockquote]:text-zinc-500 [&_blockquote]:italic [&_hr]:border-zinc-800 [&_hr]:my-6 [&_strong]:text-white [&_strong]:font-semibold [&_table]:w-full [&_table]:border-collapse [&_th]:border [&_th]:border-zinc-700 [&_th]:px-3 [&_th]:py-2 [&_th]:text-left [&_th]:text-xs [&_th]:font-semibold [&_th]:text-zinc-300 [&_th]:bg-zinc-800 [&_td]:border [&_td]:border-zinc-800 [&_td]:px-3 [&_td]:py-2 [&_td]:text-xs">
      <ReactMarkdown remarkPlugins={[remarkGfm]}>{content}</ReactMarkdown>
    </div>
  );
}
